### ISSUE TITLE
Race condition (?) in query all interfaces

### ISSUE THREAD

**Issue by irsl** [tyranid/oleviewdotnet#19]
While working on a bunch of new lightweight features for this awesome tool (expect a PR soon), I noticed "query all interfaces" skips populating interfaces of some of the COM servers in the Local Services view. The COM servers where the interfaces are not populated are random (missing ones are different every time I execute it) and changing the number of threads to 1 does not workaround the issue, I assume this has something to do with the background job accessing the TreeNode control on the UI thread.

Reproducing steps: run OVDN as an admin, open Local Services view, invoke Query all interfaces, then after it has completed, inspect some of the COM servers randomly. Around 20% of them will be empty (IUnknown only), even though they do have some interfaces defined.

(One of the new features I implemented is exporting the local services view to a csv file so it can be opened in Excel later on to have a table like view. As a quick and ugly workaround I decided to automate expanding the treenode on the UI thread; this approach indeed workarounds the issue)

**Comment by tyranid** [comment]
Yes the Query All Interface feature is deeply unreliable, especially for out-of-process services. This is because I have a timeout set to prevent the enumeration process waiting indefinitely, if the service takes a while to startup this timeout might hit and no results are returned. I'm not sure it's really worth fixing it properly.

Any PRs are welcome for new features. Though I should mention that you can dump a lot of information from the database through the PowerShell interface. If you go to the menu File -> Open PowerShell. Then in the PowerShell window run the command:

`Get-ComClass -Service | Select * | Export-Csv services.csv`

That will get all service COM classes, select all properties and export them to a CSV file. You can even view it in a table by replacing the last step with `Out-GridView`. PowerShell also gives you much more control over filtering.

**Comment by irsl** [comment]
Thanks for the explanation, it makes sense now. I share your concern about fixing this, so feel free to close this ticket.
